"""initial

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-05 20:48:18.187030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('party', sa.String(), nullable=False),
    sa.Column('chamber', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('capitol_trades_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("chamber IN ('House','Senate')", name='chamber_check'),
    sa.CheckConstraint("party IN ('D','R','I')", name='party_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capitol_trades_id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('email_1_status', sa.String(), nullable=True),
    sa.Column('email_2_status', sa.String(), nullable=True),
    sa.Column('email_3_status', sa.String(), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('total_tokens_in', sa.Integer(), nullable=True),
    sa.Column('total_tokens_out', sa.Integer(), nullable=True),
    sa.Column('est_cost_usd', sa.Float(), nullable=True),
    sa.CheckConstraint("status IN ('running','success','partial','failed')", name='status_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_date')
    )
    op.create_table('spy_daily_close',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('trade_date')
    )
    op.create_table('politician_scores',
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start_date', sa.Date(), nullable=False),
    sa.Column('window_end_date', sa.Date(), nullable=False),
    sa.Column('total_return_pct', sa.Float(), nullable=False),
    sa.Column('spy_return_pct', sa.Float(), nullable=False),
    sa.Column('alpha_vs_spy_pct', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('politician_id')
    )
    op.create_table('politician_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('disclosure_date', sa.Date(), nullable=False),
    sa.Column('amount_min_usd', sa.Integer(), nullable=True),
    sa.Column('amount_max_usd', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("side IN ('BUY','SELL')", name='side_check'),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politician_id', 'ticker', 'side', 'trade_date', 'disclosure_date', name='uq_disclosure')
    )
    op.create_index('ix_trades_disclosure_date', 'politician_trades', ['disclosure_date'], unique=False)
    op.create_index('ix_trades_politician_id', 'politician_trades', ['politician_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_politician_id', table_name='politician_trades')
    op.drop_index('ix_trades_disclosure_date', table_name='politician_trades')
    op.drop_table('politician_trades')
    op.drop_table('politician_scores')
    op.drop_table('spy_daily_close')
    op.drop_table('runs')
    op.drop_table('politicians')
    # ### end Alembic commands ###
